---
# This configuration file is used to describe different sizes
# of deployments.
#
minimal:
  nodes:
    master:
      count: 1
      cpus: 2
      memory: 2048
      storage: 20G
    worker:
      count: 1
      cpus: 2
      memory: 2048
      storage: 20G
    loadbalancer:
      count: 1
      cpus: 1
      memory: 512
      storage: 20G
    storage:
      count: 1
      cpus: 1
      memory: 512
      storage: 20G
small:
  nodes:
    master:
      count: 1
      cpus: 2
      memory: 2048
      storage: 20G
    worker:
      count: 2
      cpus: 2
      memory: 2048
      storage: 20G
    loadbalancer:
      count: 1
      cpus: 1
      memory: 1024
      storage: 20G
    storage:
      count: 1
      cpus: 1
      memory: 1024
      storage: 20G
medium:
  nodes:
    master:
      count: 3
      cpus: 2
      memory: 4096
      storage: 20G
    worker:
      count: 3
      cpus: 4
      memory: 16384
      storage: 20G
    loadbalancer:
      count: 1
      cpus: 2
      memory: 4096
      storage: 20G
    storage:
      count: 1
      cpus: 2
      memory: 4096
      storage: 20G
large:
  nodes:
    master:
      count: 3
      cpus: 4
      memory: 8192
      storage: 20G
    worker:
      count: 5
      cpus: 4
      memory: 16384
      storage: 80G
    loadbalancer:
      count: 1
      cpus: 2
      memory: 8192
      storage: 20G
    storage:
      count: 1
      cpus: 2
      memory: 8192
      storage: 100G
